// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuqKgpL0t6aI5xD4PGZ2S5KcVOlN2Xvpg',
    appId: '1:45577152565:web:8f6b9b72b303af4ee2297c',
    messagingSenderId: '45577152565',
    projectId: 'teamify-acde9',
    authDomain: 'teamify-acde9.firebaseapp.com',
    storageBucket: 'teamify-acde9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3a0kQKljnCsozoYZrvn6hTUA_PFMIZ9Y',
    appId: '1:45577152565:android:5035729b32d1416ae2297c',
    messagingSenderId: '45577152565',
    projectId: 'teamify-acde9',
    storageBucket: 'teamify-acde9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU8wL-ubTRFuCfxerpz65CUNBZMwCyhQs',
    appId: '1:45577152565:ios:a502663ebdc766d5e2297c',
    messagingSenderId: '45577152565',
    projectId: 'teamify-acde9',
    storageBucket: 'teamify-acde9.firebasestorage.app',
    iosBundleId: 'com.example.teamify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU8wL-ubTRFuCfxerpz65CUNBZMwCyhQs',
    appId: '1:45577152565:ios:a502663ebdc766d5e2297c',
    messagingSenderId: '45577152565',
    projectId: 'teamify-acde9',
    storageBucket: 'teamify-acde9.firebasestorage.app',
    iosBundleId: 'com.example.teamify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuqKgpL0t6aI5xD4PGZ2S5KcVOlN2Xvpg',
    appId: '1:45577152565:web:f6af9b178c4393dae2297c',
    messagingSenderId: '45577152565',
    projectId: 'teamify-acde9',
    authDomain: 'teamify-acde9.firebaseapp.com',
    storageBucket: 'teamify-acde9.firebasestorage.app',
  );
}
